/*
 * This source file was generated by the Gradle 'init' task
 */
package codealpha.java.gradle.app;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    private final App calculator = new App();

    @Test
    void testGetGreeting() {
        String greeting = calculator.getGreeting();
        assertNotNull(greeting, "Greeting should not be null");
        assertTrue(greeting.contains("Calculator"), "Greeting should contain 'Calculator'");
    }

    @Test
    void testAdd() {
        assertEquals(5.0, calculator.add(2.0, 3.0), 0.001, "2 + 3 should equal 5");
        assertEquals(0.0, calculator.add(-1.0, 1.0), 0.001, "-1 + 1 should equal 0");
    }

    @Test
    void testSubtract() {
        assertEquals(1.0, calculator.subtract(4.0, 3.0), 0.001, "4 - 3 should equal 1");
        assertEquals(-5.0, calculator.subtract(5.0, 10.0), 0.001, "5 - 10 should equal -5");
    }

    @Test
    void testMultiply() {
        assertEquals(6.0, calculator.multiply(2.0, 3.0), 0.001, "2 * 3 should equal 6");
        assertEquals(0.0, calculator.multiply(5.0, 0.0), 0.001, "5 * 0 should equal 0");
    }

    @Test
    void testDivide() {
        assertEquals(2.5, calculator.divide(5.0, 2.0), 0.001, "5 / 2 should equal 2.5");
        assertEquals(-1.0, calculator.divide(10.0, -10.0), 0.001, "10 / -10 should equal -1");
    }

    @Test
    void testDivideByZero() {
        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
            calculator.divide(10.0, 0.0);
        });
        assertEquals("Cannot divide by zero", exception.getMessage());
    }
}
